export const GET_PLANETS_REQUESTED = 'PLANETS/GET_PLANETS_REQUESTED'
export const GET_PLANETS_SUCCESSFUL = 'PLANETS/GET_PLANETS_SUCCESSFUL'
export const GET_PLANETS_FAILED = 'PLANETS/GET_PLANETS_FAILED'

export const GET_PLANET_DETAILS_REQUESTED = 'PLANETS/GET_PLANETS_DETAILS_REQUESTED'
export const GET_CURRENT_PLANET_DETAILS_SUCCESSFUL = 'PLANETS/GET_CURRENT_PLANET_DETAILS_SUCCESSFUL'

export const GET_FILMS_REQUESTED = 'PLANETS/GET_FILMS_REQUESTED'
export const GET_FILMS_SUCCESSFUL = 'PLANETS/GET_FILMS_SUCCESSFUL'

export const GET_RESIDENTS_REQUESTED = 'PLANETS/GET_RESIDENTS_REQUESTED'
export const GET_RESIDENTS_SUCCESSFUL = 'PLANETS/GET_RESIDENTS_SUCCESSFUL'