export const GET_PLANETS_REQUESTED = 'PLANETS/GET_PLANETS_REQUESTED'
export const GET_PLANETS_SUCCESSFUL = 'PLANETS/GET_PLANETS_SUCCESSFUL'
export const GET_PLANETS_FAILED = 'PLANETS/GET_PLANETS_FAILED'